# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' BagEnd
#' 
#' In a hole in the ground there lived a lot of cells,lol. 
#' @param arraydata expression matrix
#' @param pdata pheondata data.frame
#' @return R6Class
#' 
#' @export
#' @examples
#' sellobject <- BagEndClass$new(arraydata = arraydata,pdata = pdata)
BagEndClass <- R6::R6Class(
  "BagEnd",
  public = list(
    arraydata = NA,pdata = NA,
    initialize = function(arraydata,pdata){
      self$arraydata <- array 
      self$pdata <- pdata
      self$info()
    },
    info = function(){
      message("In a hole in the ground there lived a lot of cells,lol,this is an R6 object for singlecell object")
    }
    # more effects should be done in providing methods
  )
)
