# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' intersect_array_pdata
#' 
#' intersect select cells and interested genes
#' @param arraydata expression matrix
#' @param pdata pheondata data.frame
#' @param genelist a vector, with gene names
#' @param pdata_row2col transform the row.names of pdata into a col,default as sampleid
#' @return list
#' 
#' @export
#' @examples
#' arraydata <- readRDS("~/sell/dev/cd8_all_array.RDS")
#' pdata <- readRDS("~/sell/dev/cd8_all_meta.RDS")
#' newdata <- intersect_array_pdata(arraydata,pdata)
intersect_array_pdata <- function(arraydata,pdata,genelist = NA,pdata_row2col = "sampleid"){
  co_cell <- intersect(colnames(arraydata),rownames(pdata))
  intersect_list <- list()
  if (length(co_cell) != 0){
    intersect_list[["arraydata"]] <- arraydata[,co_cell]
    message("try transform the row.names of pdata into a col, default as sampleid")
    intersect_list[["pdata"]] <- pdata[co_cell,] %>% 
      dplyr::mutate(sampleid = rownames(.))
    if (!is.na(genelist) & sum(genelist %in% rownames(arraydata)) == length(genelist)){
      intersect_list[["arraydata"]] <- arraydata[genelist,co_cell]
    } else if (is.na(genelist)) {
      message("no filteration in the genes ")
    } else {
      stop(glue::glue("{genelist[genelist %in% rownames(arraydata)]} not found in the row.name"))
    }
  } else {
    message("0 intersection found")
  }
  return(intersect_list)
}
