# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' sell_melt
#' 
#' melt the arraydata and pdata into a long table for following plotting works
#' @param intersect_list a list object preprocessed by intersect_array_pdata function, which should has 2 items including arraydata and pdata
#' @param pdata_row2col transform the row.names of pdata into a col,default as sampleid
#' @return data.frame
#' 
#' @export
#' @examples
#' melt_df <- sell_melt(newdata)
sell_melt <- function(intersect_list,pdata_row2col = "sampleid"){
  if (class(intersect_list) != "list"){
      stop("the input should be a list object preprocessed by intersect_array_pdata function, which should has 2 items including arraydata and pdata ")
    }
  if (!(pdata_row2col %in% colnames(intersect_list[["pdata"]]))){
    stop(glue::glue("{col_sampleid} not found in the col.names of pdata"))
  } 
  message("start sell melting ")
  pdata <- intersect_list[["pdata"]]
  melt_matrix <- intersect_list[["arraydata"]] %>%
    as.data.frame() %>% 
    dplyr::mutate(Gene = rownames(.)) %>% 
    dplyr::select(all_of(c("Gene",pdata$sampleid))) %>%
    dplyr::relocate(Gene) %>% 
    tidyr::pivot_longer(cols = -Gene, 
                              names_to = pdata_row2col, 
                              values_to = "value") %>% 
    dplyr::left_join(pdata,by = pdata_row2col ) 
  return(melt_matrix)
}
