# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' seurat_encoder
#' 
#' encode our arraydata and pdata into a seurat object and perform a quick computaion
#' @param arraydata expression matrix
#' @param pdata pheondata data.frame
#' @param project project names
#' @param min.cells min.cells in initing a seurat object
#' @param min.features min.features in initing a seurat object
#' @param reduction_dims dims used in data demention reduction
#' @param Normalized apply normalized methods
#' @param Demention apply demention reduction methods
#' 
#' @return seurat_object
#' 
#' @export
#' @examples
#' seurat_object <- seurat_encoder(newdata[["arraydata"]],newdata[["pdata"]],min.cells = 0,
#'                            min.features = 0,reduction_dims = 1:5)
seurat_encoder <- function(arraydata,
                           pdata,
                           project = "SeuratProject",
                           min.cells = 3,
                           min.features = 200,
                           reduction_dims = 1:20,
                           Normalized = FALSE,
                           Demention = FALSE
                           ){
  library(dplyr)
  seurat_version <- seurat_api_detect()
  message(glue::glue("The Seurat API V{seurat_version} is used, start encoding.../n"))
  seurat_object <- Seurat::CreateSeuratObject(counts = arraydata,
                             meta.data = pdata,
                             project = project, min.cells = min.cells, min.features = min.features)
  if (Normalized){
      seurat_object <- seurat_object %>% 
        Seurat::NormalizeData() %>%
        Seurat::ScaleData()
    }
  if (Demention){
    seurat_object <- seurat_object %>% 
      Seurat::FindVariableFeatures() %>%
      Seurat::RunPCA() %>%
      Seurat::RunUMAP(dims = reduction_dims) %>%
      Seurat::RunTSNE()
  }
    
  return(seurat_object)
}
