# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' seurat_decoder
#' 
#' extract data from the seurat container
#' @param seurat_object the seurat object
#' @param HasNormalized the seurat object has normalized when TRUE
#' @param HasZscored the seurat object has Zscored when TRUE
#' @param PCA the seurat object has performed PCA when TRUE
#' @param UMAP the seurat object has performed UMAP when TRUE
#' @param TSNE the seurat object has performed TSNE when TRUE
#' @return list
#' 
#' @export
#' @examples
#' sell_list <- seurat_decoder(seurat_object)
seurat_decoder <- function(seurat_object,
                           HasNormalized = FALSE,
                           HasZscored = FALSE,
                           PCA = FALSE,
                           UMAP = FALSE,
                           TSNE = FALSE){
  library(dplyr)
  seurat_version <- seurat_api_detect()
  message(glue::glue("The Seurat API V{seurat_version} is used, start decoding.../n HasNormalized & HasZscored are default as FALSE "))
  decode_list <- list()
  if (seurat_version < 5){
    decode_list[["meta_data"]] <- seurat_object@meta.data
    decode_list[["counts"]] <- seurat_object@assays$RNA@counts
    if (HasNormalized){
      decode_list[["Normalized_data"]] <- seurat_object@assays$RNA@data
    }
    if (HasZscored){
      decode_list[["scale_data"]] <- seurat_object@assays$RNA@scale.data
    }
  } else {
    decode_list[["meta_data"]] <- seurat_object@meta.data
    decode_list[["counts"]] <- seurat_object[["RNA"]]$counts
    if (HasNormalized){
      decode_list[["Normalized_data"]] <- seurat_Object[["RNA"]]$data
    }
    if (HasZscored){
      decode_list[["scale_data"]] <- seurat_Object[["RNA"]]$scale.data
    }
  }
  if (PCA){
    decode_list[["PCA"]] <- Embeddings(seurat_object,"pca")
  }
  if (UMAP){
    decode_list[["UMAP"]] <- Embeddings(seurat_object,"umap")
  }
  if (TSNE){
    decode_list[["TSNE"]] <- Embeddings(seurat_object,"tsne")
  }
  return(decode_list)
}

