# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' seurat_api_detect
#' 
#' detect seurat api version, if NULL, try to install seurat packages
#' 
#' @return num
#' 
#' @export
#' @examples
#' seurat_api_detect()
seurat_api_detect <- function(){
  library(dplyr)
  packagelist <- installed.packages() %>%
    as.data.frame()
  seurat_exist <- "Seurat" %in% packagelist$Package
  message("detecting Seurat package ...")
  while (!seurat_exist) {
    message("Seurat package not found, we will install it for you...")
    pak::pak("Seurat")
    packagelist <- installed.packages() %>%
      as.data.frame()
    seurat_exist <- "Seurat" %in% packagelist$Package
    if (!seurat_exist) {
      message("Installation of Seurat failed. Please try again or install it manually.")
      break
    }
  }
  message("Confirming Seurat package API version ...")
  packagelist <- packagelist %>%
    dplyr::filter(Package %in% "Seurat")
  seurat_version <- stringr::str_sub(packagelist$Version[1],1,1) %>% as.numeric()
  message(glue::glue("The Seurat API V{seurat_version} is used..."))
  return(seurat_version)
}
